FROM rust:1.92.0

RUN apt-get update && apt-get install -y build-essential \
pkg-config libssl-dev curl lld && \
rm -rf /var/lib/apt/lists/*

RUN rustup target add wasm32-unknown-unknown
RUN cargo install dioxus-cli --version 0.7.2
